# shgittp v0.4.13 Configuration
# ~/.config/shgittp/config

# Global defaults
[default]
repo = ""
branch = develop
dir = .dot
tree = ""
run = ""
user = ""

[dev@devbox]
repo = git@github.com:robchrob/dotfiles-bare.git
branch = minimal
dir = .dot
user = dev

[endpoint]
repo = git@github.com:robchrob/dotfiles-bare.git
branch = minimal
dir = .dot
user = dev
run = bash .config/setup.sh

repo_root = git@github.com:robchrob/dotfiles-bare.git
branch_root = minimal-root
dir_root = .cfg
tree_root = /root
user_root = root
run_root = sh .config/setup.sh
